repos:
-   repo: https://github.com/lescuer97/pre-commit-rust
    rev: 280fbc455c6ac7ebba62d9d63fe26d800189c0a4
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: cargo-test

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0  # Use the ref you want to point at
    hooks:
    -   id: deno-fmt
    -   id: deno-lint
    -   id: deno-test
