[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "./src/build.rs"

[dependencies]
prost = "0.11"
prost-types = "0.11"
actix-web = "4.3"

[build-dependencies]
prost-build = { version = "0.11" }
fs_extra = "1.3.0"

