name: Deno CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
          deno: ["v1.x", "nightly"]

      steps:
        - name: Set up repo
          working-directory: ./front_end
          uses: actions/checkout@v2

        - name: Set up Deno
          working-directory: ./front_end
          uses: denolib/setup-deno@v2
          with:
            deno-version: ${{ matrix.deno }}

        - name: Cache Dependencies
          working-directory: ./front_end
          run: deno cache deps.ts

        - name: Run Tests
          working-directory: ./front_end
          run: deno test -A --unstable
