name: Deno CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./front_end

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        deno: ["v1.x"]

    steps:
    - uses: actions/setup-node@v3
    # - uses: arduino/setup-protoc@v1

    - name: Set up repo
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno }}

    # - name: generate types
    #   run: |
    #     npm install -g protoc-gen-ts
    #     deno task parseProto


    - name: Run Tests
      run: deno test -A --unstable
