name: Rust server
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    # - uses: arduino/setup-protoc@v1

    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup install nightly

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Lint
      run: |
        cargo fmt -- --check
        # cargo clippy -- -D warnings

    - name: Test
      env: # Or as an environment variable
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ENVIROMENT: ${{ secrets.ENVIROMENT }}
        SECRET_FOR_JWT: ${{ secrets.SECRET_FOR_JWT }}
      run: |
        # echo DATABASE_URL="$DATABASE_URL" >> .env
        cargo check
        cargo test --all

    - name: Build
      run: |
        cargo build --release
