name: Rust server
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup install nightly

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Test
      run: |
        cargo check
        cargo test --all

    - name: Build
      run: |
        cargo build --release
